getting "Error CS0120 An object reference is required for the non-static field, method, or property 'Movie.Title' ..WebApplication1\WebApplication1\Views\Home\Index.cshtml" not sure why